-- CREATE UNIQUE AUTO GENERATED NOT NULL PRIMARY KEY ID
-- TASK 6
CREATE DATABASE IF NOT EXISTS `hbtn_0d_usa`;
CREATE TABLE IF NOT EXISTS `states` (
	PRIMARY KEY (`id`),
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(256) NOT NULL
);
